services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    ports:
      - "9200:9200"
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
    networks:
      - rabbitmq
    depends_on:
      - rabbitmq

  database:
    image: redis
    volumes:
      - /tmp/database:/data
    networks:
      - database
    command: redis-server --save 60 1 --loglevel warning

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    networks:
      - rabbitmq
    expose:
      - 5672
      - 15672
    ports:
      - "15672:15672"
    volumes:
      - rabbbitmq_data:/var/lib/rabbitmq
      - rabbbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  backend:
    build: ./backend
    networks:
      - database
      - rabbitmq
      - default
    expose:
      - 8080
    environment:
      - PORT=8080
    ports:
      - "8081:8080"
    depends_on:
      - database
      - rabbitmq
    restart: on-failure

  frontend:
    build: ./frontend
    environment:
      - PORT=8080
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - default

networks:
  default:
    driver: bridge
  database: {}
  rabbitmq: {}

volumes:
  rabbbitmq_data:
  rabbbitmq_logs:
