apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/redis-volume/
  storageClassName: redis
